# Generated by Django 5.2.4 on 2025-07-12 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person contacting us', max_length=100)),
                ('email', models.EmailField(help_text='Email address for replies', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=200)),
                ('message', models.TextField(help_text='The actual message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', help_text='Current status of this message', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this message was received')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this message was resolved', null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of your blog post', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title (auto-generated)', max_length=200, unique=True)),
                ('content', models.TextField(help_text='The main content of your blog post')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary of the post (optional)', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='The current status of this post', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='How many times this post has been viewed')),
                ('is_featured', models.BooleanField(default=False, help_text='Should this post be featured on the homepage?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this post was last updated')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this post was published', null=True)),
                ('author', models.ForeignKey(help_text='Who wrote this post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posts', models.ManyToManyField(blank=True, help_text='Blog posts in this category', related_name='categories', to='main_app.blogpost')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Your comment content', max_length=1000)),
                ('is_approved', models.BooleanField(default=True, help_text='Is this comment approved for display?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this comment was posted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this comment was last edited')),
                ('author', models.ForeignKey(help_text='Who wrote this comment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='The blog post this comment is on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.blogpost')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself!', max_length=500)),
                ('birth_date', models.DateField(blank=True, help_text='Your birth date (optional)', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pics/')),
                ('website', models.URLField(blank=True, help_text='Your personal website (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this profile was last updated')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'created_at'], name='main_app_bl_status_2084d9_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', 'status'], name='main_app_bl_author__25b654_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='main_app_co_post_id_6e9509_idx'),
        ),
    ]
